server:
  port: 9003

spring:
  application:
    name: notification-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/notificationdb
  jpa:
    show-sql: true