server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,gateway,health,hystrix.stream
      cors:
        allowed-origins: http://localhost:3000
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP