server:
  port: 8761

eureka:
  instance:
    hostname: localhost
#    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-repository: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      discovery:
        enabled: true