server:
  port: 9004

spring:
  application:
    name: inventory-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/inventorydb
  jpa:
    show-sql: true